# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-27 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('actuator_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('technical_name', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=False)),
                ('state_cicle1', models.BooleanField(default=False)),
                ('time_cicle1_begin', models.TimeField(blank=True, null=True)),
                ('time_cicle1_end', models.TimeField(blank=True, null=True)),
                ('state_cicle2', models.BooleanField(default=False)),
                ('time_cicle2_begin', models.TimeField(blank=True, null=True)),
                ('time_cicle2_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActuatorConfiguration',
            fields=[
                ('actuator_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('digital_port1', models.CharField(default='', max_length=10)),
                ('description_digital_port1', models.CharField(default='', max_length=10)),
                ('digital_port2', models.CharField(default='', max_length=10)),
                ('description_digital_port2', models.CharField(default='', max_length=10)),
                ('digital_port3', models.CharField(default='', max_length=10)),
                ('description_digital_port3', models.CharField(default='', max_length=10)),
                ('digital_port4', models.CharField(default='', max_length=10)),
                ('description_digital_port4', models.CharField(default='', max_length=10)),
                ('digital_port5', models.CharField(default='', max_length=10)),
                ('description_digital_port5', models.CharField(default='', max_length=10)),
                ('digital_port6', models.CharField(default='', max_length=10)),
                ('description_digital_port6', models.CharField(default='', max_length=10)),
                ('actuator_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hyp_app.Actuator')),
            ],
        ),
        migrations.CreateModel(
            name='FilesAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_file_id', models.CharField(default='', max_length=10)),
                ('files_attachments', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogDataActuator',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_time_data_log', models.DateTimeField(default=django.utils.timezone.now)),
                ('actuator_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hyp_app.Actuator')),
            ],
        ),
        migrations.CreateModel(
            name='LogDataSensor',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('register1', models.CharField(default='', max_length=25)),
                ('register1_measure', models.CharField(default='', max_length=20)),
                ('register2', models.CharField(default='', max_length=25)),
                ('register2_measure_measure', models.CharField(default='', max_length=20)),
                ('register3', models.CharField(default='', max_length=25)),
                ('register3_measure', models.CharField(default='', max_length=20)),
                ('date_time_data_log', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MicrocontrollerAttributes',
            fields=[
                ('mca_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=30)),
                ('board_name', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('digital_ports', models.CharField(default='', max_length=100)),
                ('number_digital_ports', models.IntegerField()),
                ('pwm_ports', models.CharField(default='', max_length=100)),
                ('number_pwm_ports', models.IntegerField()),
                ('analog_ports', models.CharField(default='', max_length=100)),
                ('number_analog_ports', models.IntegerField()),
                ('rx_tx_ports', models.CharField(default='', max_length=100)),
                ('number_rx_tx_ports', models.CharField(default='', max_length=100)),
                ('sda_scl_ports', models.CharField(default='', max_length=100)),
                ('number_sda_scl_ports', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('technical_name', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=False)),
                ('state_cicle1', models.BooleanField(default=False)),
                ('time_cicle1_begin', models.TimeField(blank=True, null=True)),
                ('time_cicle1_end', models.TimeField(blank=True, null=True)),
                ('state_cicle2', models.BooleanField(default=False)),
                ('time_cicle2_begin', models.TimeField(blank=True, null=True)),
                ('time_cicle2_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorConfiguration',
            fields=[
                ('sensor_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('digital_port1', models.CharField(default='', max_length=10)),
                ('description_digital_port1', models.CharField(default='', max_length=10)),
                ('mode_digital_port1', models.CharField(default='', max_length=10)),
                ('digital_port2', models.CharField(default='', max_length=10)),
                ('description_digital_port2', models.CharField(default='', max_length=10)),
                ('mode_digital_port2', models.CharField(default='', max_length=10)),
                ('digital_port3', models.CharField(default='', max_length=10)),
                ('description_digital_port3', models.CharField(default='', max_length=10)),
                ('mode_digital_port3', models.CharField(default='', max_length=10)),
                ('analog_port1', models.CharField(default='', max_length=10)),
                ('description_analog_port1', models.CharField(default='', max_length=10)),
                ('mode_analog_port1', models.CharField(default='', max_length=10)),
                ('analog_port2', models.CharField(default='', max_length=10)),
                ('description_analog_port2', models.CharField(default='', max_length=10)),
                ('mode_analog_port2', models.CharField(default='', max_length=10)),
                ('number_ports_digital', models.IntegerField()),
                ('number_ports_analog', models.IntegerField()),
                ('sensor_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hyp_app.Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='logdatasensor',
            name='sensor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hyp_app.Sensor'),
        ),
    ]
