# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-05 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('actuator_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('technical_name', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='', max_length=100)),
                ('is_activated', models.BooleanField(default=False)),
                ('actuator_photo', models.FileField(blank='True', null='True', upload_to='actuator_photo')),
                ('actuator_document_1', models.FileField(blank='True', null='True', upload_to='actuator_document_1')),
                ('actuator_document_2', models.FileField(blank='True', null='True', upload_to='actuator_document_2')),
                ('actuator_document_3', models.FileField(blank='True', null='True', upload_to='actuator_document_3')),
            ],
        ),
        migrations.CreateModel(
            name='ActuatorConfiguration',
            fields=[
                ('actuator_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('digital_port1', models.CharField(default='', max_length=10)),
                ('description_digital_port1', models.CharField(default='', max_length=10)),
                ('digital_port2', models.CharField(default='', max_length=10)),
                ('description_digital_port2', models.CharField(default='', max_length=10)),
                ('digital_port3', models.CharField(default='', max_length=10)),
                ('description_digital_port3', models.CharField(default='', max_length=10)),
                ('digital_port4', models.CharField(default='', max_length=10)),
                ('description_digital_port4', models.CharField(default='', max_length=10)),
                ('digital_port5', models.CharField(default='', max_length=10)),
                ('description_digital_port5', models.CharField(default='', max_length=10)),
                ('digital_port6', models.CharField(default='', max_length=10)),
                ('description_digital_port6', models.CharField(default='', max_length=10)),
                ('actuator_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hyp_app.Actuator')),
            ],
        ),
        migrations.CreateModel(
            name='FilesAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_file_id', models.CharField(default='', max_length=10)),
                ('files_attachments', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogDataActuator',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_time_data_log', models.DateTimeField(default=django.utils.timezone.now)),
                ('actuator_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hyp_app.Actuator')),
            ],
        ),
        migrations.CreateModel(
            name='LogDataSensor',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('register1', models.CharField(default='', max_length=25)),
                ('register1_measure', models.CharField(default='', max_length=20)),
                ('register2', models.CharField(default='', max_length=25)),
                ('register2_measure_measure', models.CharField(default='', max_length=20)),
                ('register3', models.CharField(default='', max_length=25)),
                ('register3_measure', models.CharField(default='', max_length=20)),
                ('date_time_data_log', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Microcontroller',
            fields=[
                ('mc_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_board', models.CharField(default='', max_length=30)),
                ('board_name', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='', max_length=100)),
                ('digital_ports', models.CharField(default='', max_length=1000)),
                ('number_digital_ports', models.CharField(default='', max_length=2)),
                ('pwm_ports', models.CharField(default='', max_length=100)),
                ('number_pwm_ports', models.CharField(default='', max_length=2)),
                ('analog_ports', models.CharField(default='', max_length=100)),
                ('number_analog_ports', models.CharField(default='', max_length=2)),
                ('microcontroller_photo', models.FileField(blank='True', null='True', upload_to='actuator_photo')),
                ('is_activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MQTTLog',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('reference', models.CharField(default='', max_length=50)),
                ('value', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('time', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('technical_name', models.CharField(default='', max_length=50)),
                ('type_signal', models.CharField(default='', max_length=10)),
                ('lib_code', models.CharField(default='', max_length=10)),
                ('description', models.TextField(default='')),
                ('digital_ports_quant', models.CharField(default='', max_length=2)),
                ('analog_ports_quant', models.CharField(default='', max_length=2)),
                ('is_activated', models.BooleanField(default=False)),
                ('sensor_photo', models.FileField(blank='True', null='True', upload_to='sensor_photo')),
                ('sensor_document_1', models.FileField(blank='True', null='True', upload_to='sensor_document_1')),
                ('sensor_document_2', models.FileField(blank='True', null='True', upload_to='sensor_document_2')),
                ('sensor_document_3', models.FileField(blank='True', null='True', upload_to='sensor_document_3')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorConfiguration',
            fields=[
                ('sensor_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('digital_port1', models.CharField(default='', max_length=10)),
                ('description_digital_port1', models.CharField(default='', max_length=10)),
                ('mode_digital_port1', models.CharField(default='', max_length=10)),
                ('digital_port2', models.CharField(default='', max_length=10)),
                ('description_digital_port2', models.CharField(default='', max_length=10)),
                ('mode_digital_port2', models.CharField(default='', max_length=10)),
                ('digital_port3', models.CharField(default='', max_length=10)),
                ('description_digital_port3', models.CharField(default='', max_length=10)),
                ('mode_digital_port3', models.CharField(default='', max_length=10)),
                ('analog_port1', models.CharField(default='', max_length=10)),
                ('description_analog_port1', models.CharField(default='', max_length=10)),
                ('mode_analog_port1', models.CharField(default='', max_length=10)),
                ('analog_port2', models.CharField(default='', max_length=10)),
                ('description_analog_port2', models.CharField(default='', max_length=10)),
                ('mode_analog_port2', models.CharField(default='', max_length=10)),
                ('number_ports_digital', models.IntegerField()),
                ('number_ports_analog', models.IntegerField()),
                ('sensor_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hyp_app.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(default='', max_length=50)),
                ('topic_path', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='logdatasensor',
            name='sensor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hyp_app.Sensor'),
        ),
    ]
