# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-12 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='topic_name',
        ),
    ]
