# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-04 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actuator',
            old_name='is_active',
            new_name='is_activated',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='is_active',
            new_name='is_activated',
        ),
        migrations.AddField(
            model_name='actuator',
            name='type_sensor',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sensor',
            name='lib_code',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sensor',
            name='type_sensor',
            field=models.CharField(default='', max_length=30),
        ),
    ]
