# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-25 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0002_auto_20190224_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='total_cycle',
            new_name='end_permanence_cycle',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='days',
        ),
        migrations.AddField(
            model_name='cycle',
            name='start_permanence_cycle',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='total_permanence_cycle',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
