# Generated by Django 2.1.7 on 2019-09-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('passwd', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='peripheral',
            name='firebase_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
