# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-12 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0002_remove_topics_topic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peripheral',
            old_name='topic_name',
            new_name='topic_nome',
        ),
    ]
