# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-11 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0002_auto_20180204_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='date_time_create',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
