# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-05 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0002_remove_mqttlog_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttlog',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
