# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-12 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0003_auto_20190212_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peripheral',
            old_name='topic_nome',
            new_name='topic_name',
        ),
    ]
