# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0003_sensor_date_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='lib_code',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='technical_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type_sensor',
            field=models.CharField(default='', max_length=35),
        ),
    ]
