# Generated by Django 2.1.7 on 2019-02-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0003_auto_20190225_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='actuador_record_state',
        ),
        migrations.AlterField(
            model_name='cycle',
            name='end_cycle',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='start_cycle',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
