# Generated by Django 2.1.7 on 2019-02-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0004_auto_20190226_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='total_permanence_cycle',
        ),
    ]
