# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-12 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0004_auto_20180311_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='type_sensor',
            new_name='type_signal',
        ),
    ]
