# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-05 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0004_auto_20180805_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mqttlog',
            old_name='dateTime',
            new_name='timeDate',
        ),
        migrations.RenameField(
            model_name='mqttlog',
            old_name='hourTime',
            new_name='timeHour',
        ),
    ]
