# Generated by Django 2.1.7 on 2019-02-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0005_remove_cycle_total_permanence_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='start_cycle',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
