# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-12 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0005_auto_20180312_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='analog_ports_quant',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='sensor',
            name='digital_ports_quant',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='lib_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type_signal',
            field=models.CharField(default='', max_length=10),
        ),
    ]
