# Generated by Django 2.1.7 on 2019-02-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0006_auto_20190227_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='start_cycle',
            new_name='start_time',
        ),
    ]
