# Generated by Django 2.1.7 on 2019-02-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0007_auto_20190227_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='end_cycle',
            new_name='end_time',
        ),
    ]
