# Generated by Django 2.1.7 on 2019-02-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0008_auto_20190227_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
