# Generated by Django 2.1.7 on 2019-02-28 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0009_auto_20190227_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='time_test',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
