# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-17 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0009_auto_20180317_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_photo',
        ),
    ]
