# Generated by Django 2.1.7 on 2019-02-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0010_cycle_time_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='time_test',
            field=models.DateTimeField(null=True),
        ),
    ]
