# Generated by Django 2.1.7 on 2019-02-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0011_auto_20190228_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='time_test',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
