# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-17 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0011_sensor_sensor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_photo',
            field=models.FileField(blank='True', null='True', upload_to='sensor_photo'),
        ),
    ]
