# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-19 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0012_auto_20180317_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_document_1',
            field=models.FileField(blank='True', null='True', upload_to='sensor_document_1'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_document_2',
            field=models.FileField(blank='True', null='True', upload_to='sensor_document_2'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_document_3',
            field=models.FileField(blank='True', null='True', upload_to='sensor_document_3'),
        ),
    ]
