# Generated by Django 2.1.7 on 2019-03-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0013_auto_20190228_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='end_permanence_cycle',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='start_permanence_cycle',
        ),
        migrations.AddField(
            model_name='cycle',
            name='end_cycle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='start_cycle',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
