# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-19 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0013_auto_20180319_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
