# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-28 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0014_sensor_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator',
            name='state_cicle1',
        ),
        migrations.RemoveField(
            model_name='actuator',
            name='state_cicle2',
        ),
        migrations.RemoveField(
            model_name='actuator',
            name='time_cicle1_begin',
        ),
        migrations.RemoveField(
            model_name='actuator',
            name='time_cicle1_end',
        ),
        migrations.RemoveField(
            model_name='actuator',
            name='time_cicle2_begin',
        ),
        migrations.RemoveField(
            model_name='actuator',
            name='time_cicle2_end',
        ),
        migrations.RemoveField(
            model_name='actuator',
            name='type_sensor',
        ),
        migrations.AddField(
            model_name='actuator',
            name='sensor_photo',
            field=models.FileField(blank='True', null='True', upload_to='sensor_photo'),
        ),
    ]
