# Generated by Django 2.1.7 on 2019-03-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0014_auto_20190303_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='time_test',
        ),
    ]
