# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-28 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0015_auto_20180328_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator',
            name='sensor_photo',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='date_time_create',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='state_cicle1',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='state_cicle2',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='time_cicle1_begin',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='time_cicle1_end',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='time_cicle2_begin',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='time_cicle2_end',
        ),
        migrations.AddField(
            model_name='actuator',
            name='actuator_document_1',
            field=models.FileField(blank='True', null='True', upload_to='actuator_document_1'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='actuator_document_2',
            field=models.FileField(blank='True', null='True', upload_to='actuator_document_2'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='actuator_document_3',
            field=models.FileField(blank='True', null='True', upload_to='actuator_document_3'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='actuator_photo',
            field=models.FileField(blank='True', null='True', upload_to='actuator_photo'),
        ),
    ]
