# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-30 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0016_auto_20180328_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MicrocontrollerAttributes',
            new_name='Microcontroller',
        ),
    ]
