# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-30 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0017_auto_20180330_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microcontroller',
            old_name='mca_id',
            new_name='mc_id',
        ),
        migrations.RenameField(
            model_name='microcontroller',
            old_name='type',
            new_name='type_board',
        ),
    ]
