# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-30 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0018_auto_20180330_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
