# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-30 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0019_auto_20180330_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microcontroller',
            name='number_rx_tx_ports',
        ),
        migrations.RemoveField(
            model_name='microcontroller',
            name='number_sda_scl_ports',
        ),
        migrations.RemoveField(
            model_name='microcontroller',
            name='rx_tx_ports',
        ),
        migrations.RemoveField(
            model_name='microcontroller',
            name='sda_scl_ports',
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='number_analog_ports',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='number_digital_ports',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='microcontroller',
            name='number_pwm_ports',
            field=models.CharField(default='', max_length=2),
        ),
    ]
