# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-01 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0020_auto_20180330_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcontroller',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='microcontroller',
            name='microcontroller_photo',
            field=models.FileField(blank='True', null='True', upload_to='actuator_photo'),
        ),
    ]
