# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-03 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyp_app', '0021_auto_20180401_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcontroller',
            name='digital_ports',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
